### ISSUE TITLE
getEntityManagerForClass($class) How work with Multi Entity Manager for the same class

### ISSUE THREAD

**Issue by acrozes** [doctrine/common#313]
My case use symfony and sonata admin.
My symfony conf is:

```
    orm:
        entity_managers:
            fr:
                connection: fr
                mappings:
                    ODNewsBundle: ~
            en:
                connection: en
                mappings:
                    ODNewsBundle: ~
```

So I have a database, a connection, and an entityManger for each locale I need.

SonataAdmin use getEntityManagerForClass($class) to find and work with an entityManager, but for the same class, I have en entityManager "fr" or "en" ... so what can I do ? 

Presently, sonata admin get the first one ...

Thanks
