### ISSUE TITLE
Can't Export/Dump Base Data of Single-Table Inheritance Entity

### ISSUE THREAD

**Issue by msypes** [doctrine/common#795]
I think this is a bug, but it could be I don't know what I'm doing:
I have a single-table inheritance table specifying a pair of related entities. There's an abstract class for the base of shared data, discriminator column, and concrete entities extending the base with their unique properties - No problem.
I tried getting an output display of an entity and found that with either `\Doctrine\Common\Util\Debug::export()` or `\Doctrine\Common\Util\Debug::dump()` but the shared data doesn't come through, only what's specific to the child class.

Consider the following YAML files:
```
#Abstract Base Entity
ME\MyBundle\Entity\BaseEntity:
    type: entity
    table: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
        length: 10
    discriminatorMap:
        type1: ChildType1
        type2: ChildType2

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            options:
                unsigned: true

    fields:
        shared_property:
            type: smallint

    manyToOne:
        shared_reference_entity:
            targetEntity: shared_reference
            inversedBy: parent
            cascade: [persist]
            joinColumn:
                name: parent_id
                referencedColumnName: id

#Child Entity Type 1
ME\MyBundle\Entity\ChildType1:
    type: entity
    extends: BaseEntity

    manyToOne:
        child_reference:
            targetEntity: TypeOneReference
            joinColumn:
                name: reference_id
                referencedColumnName: id

#Child Entity Type 2
ME\MyBundle\Entity\ChildType2:
    type: entity
    extends: BaseEntity

    manyToOne:
        child_reference:
            targetEntity: TypeTwoReference
            joinColumn:
                name: reference_id
                referencedColumnName: id
```

Now some PHP code from a Symfony project:
```
$item = $this->getDoctrine()->getRepository('MEMyBundle:ChildType1')->find(1);
\Doctrine\Common\Util\Debug::dump($item, 2);
```
Will only display information for child_reference, and none of the shared data, _i.e._, the id, nor the shared_reference.
